//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTDEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDB
    {
        public int id { get; set; }
        public string user_login { get; set; }
        public string user_pswd { get; set; }
    }
}
